// Curated dataset for the Discover page: well-known NL employers that are
// popular with internationals, tagged by industry + job function.
// Sponsor status is NEVER taken from this file — every company is verified
// against the IND register at build time (see scripts/build-data.mjs).
// `registerName` is the (approximate) legal name used for register matching
// when it differs from the everyday brand name.

export const INDUSTRIES = [
  { id: "finance", label: "Finance & Banking", emoji: "🏦" },
  { id: "consulting", label: "Consulting", emoji: "📊" },
  { id: "fintech", label: "Payments & Fintech", emoji: "💳" },
  { id: "tech", label: "Tech & Software", emoji: "💻" },
  { id: "consumer", label: "Consumer & Retail", emoji: "🛒" },
  { id: "energy", label: "Energy", emoji: "⚡" },
  { id: "health", label: "Health & Pharma", emoji: "🧬" },
  { id: "hardware", label: "Semiconductors & Hardware", emoji: "🔬" },
  { id: "logistics", label: "Logistics & Mobility", emoji: "🚚" },
  { id: "media", label: "Media & Creative", emoji: "🎨" },
] as const;
export type IndustryId = (typeof INDUSTRIES)[number]["id"];

export const FUNCTIONS = [
  { id: "front_office", label: "Front office / Investing" },
  { id: "strategy", label: "Strategy & Consulting" },
  { id: "finance_fpa", label: "Finance & FP&A" },
  { id: "data", label: "Data & Analytics" },
  { id: "engineering", label: "Engineering" },
  { id: "product", label: "Product" },
  { id: "sales_marketing", label: "Sales & Marketing" },
  { id: "operations", label: "Operations & Admin" },
  { id: "hr_legal", label: "HR & Legal" },
] as const;
export type FunctionId = (typeof FUNCTIONS)[number]["id"];

export type Company = {
  name: string;
  registerName?: string;
  industry: IndustryId;
  functions: FunctionId[];
  city: string;
  blurb?: string;
  careersUrl?: string;
};

export const COMPANIES: Company[] = [
  // ── Finance & Banking ────────────────────────────────────────────────
  { name: "ING", registerName: "ING Bank", industry: "finance", city: "Amsterdam", blurb: "Global universal bank; large graduate programmes in finance, risk and data.", functions: ["front_office", "finance_fpa", "strategy", "data", "engineering", "operations"], careersUrl: "https://www.ing.jobs" },
  { name: "ABN AMRO", registerName: "ABN AMRO Bank", industry: "finance", city: "Amsterdam", blurb: "Dutch bank with strong corporate banking and clearing arms.", functions: ["front_office", "finance_fpa", "strategy", "data", "operations"] },
  { name: "Rabobank", registerName: "Coöperatieve Rabobank", industry: "finance", city: "Utrecht", blurb: "Cooperative bank, global leader in food & agri finance.", functions: ["front_office", "finance_fpa", "strategy", "data", "operations"], careersUrl: "https://rabobank.jobs" },
  { name: "NIBC Bank", industry: "finance", city: "The Hague", blurb: "Mid-market corporate & investment bank.", functions: ["front_office", "finance_fpa", "data", "operations"] },
  { name: "Van Lanschot Kempen", industry: "finance", city: "Amsterdam", blurb: "Wealth management and merchant banking boutique.", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Triodos Bank", industry: "finance", city: "Driebergen", blurb: "Sustainable bank financing positive-impact sectors.", functions: ["front_office", "finance_fpa", "data", "operations"] },
  { name: "NN Group", industry: "finance", city: "The Hague", blurb: "Insurance and asset-management group.", functions: ["front_office", "finance_fpa", "data", "operations", "hr_legal"] },
  { name: "APG Asset Management", industry: "finance", city: "Amsterdam", blurb: "€500bn+ pension investor for ABP — one of the world's largest.", functions: ["front_office", "finance_fpa", "data", "operations"] },
  { name: "PGGM", industry: "finance", city: "Zeist", blurb: "Pension investor for healthcare fund PFZW.", functions: ["front_office", "finance_fpa", "data", "operations"] },
  { name: "Robeco", industry: "finance", city: "Rotterdam", blurb: "Quant and sustainable-investing asset manager.", functions: ["front_office", "finance_fpa", "data"] },
  { name: "Aegon Asset Management", registerName: "Aegon", industry: "finance", city: "The Hague", blurb: "Global asset manager of the Aegon group.", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Achmea Investment Management", registerName: "Achmea Interne Diensten", industry: "finance", city: "Zeist", blurb: "Pension and insurance asset manager.", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "AlpInvest Partners", industry: "finance", city: "Amsterdam", blurb: "Carlyle's private-equity fund investor: primaries, secondaries, co-investments.", functions: ["front_office", "finance_fpa", "data"] },
  { name: "Waterland Private Equity", industry: "finance", city: "Bussum", blurb: "Mid-market buy-and-build private equity firm.", functions: ["front_office", "finance_fpa"] },
  { name: "Optiver", industry: "finance", city: "Amsterdam", blurb: "Market maker famous for trading, quant and tech graduate roles.", functions: ["front_office", "data", "engineering", "operations"], careersUrl: "https://optiver.com/working-at-optiver/" },
  { name: "IMC Trading", registerName: "IMC", industry: "finance", city: "Amsterdam", blurb: "Technology-driven proprietary trading firm.", functions: ["front_office", "data", "engineering", "operations"] },
  { name: "Flow Traders", industry: "finance", city: "Amsterdam", blurb: "Leading ETP liquidity provider.", functions: ["front_office", "data", "engineering", "operations"], careersUrl: "https://www.flowtraders.com/careers" },

  // ── Consulting ───────────────────────────────────────────────────────
  { name: "McKinsey & Company", industry: "consulting", city: "Amsterdam", blurb: "Top-tier strategy consulting.", functions: ["strategy", "data"], careersUrl: "https://www.mckinsey.com/careers" },
  { name: "Boston Consulting Group", registerName: "The Boston Consulting Group", industry: "consulting", city: "Amsterdam", blurb: "Top-tier strategy consulting.", functions: ["strategy", "data"], careersUrl: "https://careers.bcg.com" },
  { name: "Bain & Company", industry: "consulting", city: "Amsterdam", blurb: "Top-tier strategy consulting; strong PE due-diligence practice.", functions: ["strategy", "data"], careersUrl: "https://www.bain.com/careers" },
  { name: "Kearney", industry: "consulting", city: "Amsterdam", blurb: "Global strategy and operations consulting.", functions: ["strategy", "operations"] },
  { name: "Roland Berger", industry: "consulting", city: "Amsterdam", blurb: "European strategy consultancy.", functions: ["strategy"] },
  { name: "OC&C Strategy Consultants", industry: "consulting", city: "Rotterdam", blurb: "Strategy boutique, strong in consumer and retail.", functions: ["strategy"] },
  { name: "Deloitte", industry: "consulting", city: "Amsterdam", blurb: "Big 4: consulting, financial advisory, audit, tax.", functions: ["strategy", "finance_fpa", "data", "hr_legal"] },
  { name: "PwC", registerName: "PricewaterhouseCoopers", industry: "consulting", city: "Amsterdam", blurb: "Big 4: deals, consulting, audit, tax.", functions: ["strategy", "finance_fpa", "data", "hr_legal"] },
  { name: "EY", registerName: "Ernst & Young", industry: "consulting", city: "Amsterdam", blurb: "Big 4: strategy & transactions, consulting, audit.", functions: ["strategy", "finance_fpa", "data", "hr_legal"] },
  { name: "KPMG", industry: "consulting", city: "Amstelveen", blurb: "Big 4: advisory, deal advisory, audit.", functions: ["strategy", "finance_fpa", "data", "hr_legal"] },
  { name: "Accenture", industry: "consulting", city: "Amsterdam", blurb: "Strategy, technology and operations consulting at scale.", functions: ["strategy", "data", "engineering", "operations"], careersUrl: "https://www.accenture.com/nl-en/careers" },

  // ── Payments & Fintech ───────────────────────────────────────────────
  { name: "Adyen", industry: "fintech", city: "Amsterdam", blurb: "Global payments platform for enterprises — NL fintech flagship.", functions: ["engineering", "product", "data", "finance_fpa", "sales_marketing", "operations"], careersUrl: "https://www.adyen.com/careers" },
  { name: "Mollie", industry: "fintech", city: "Amsterdam", blurb: "Payments for SMEs across Europe.", functions: ["engineering", "product", "data", "sales_marketing", "finance_fpa"], careersUrl: "https://www.mollie.com/careers" },
  { name: "bunq", industry: "fintech", city: "Amsterdam", blurb: "Challenger bank 'of The Free'.", functions: ["engineering", "product", "data", "operations"], careersUrl: "https://www.bunq.com/careers" },
  { name: "Backbase", industry: "fintech", city: "Amsterdam", blurb: "Engagement banking software used by banks worldwide.", functions: ["engineering", "product", "sales_marketing", "operations"] },
  { name: "Bitvavo", industry: "fintech", city: "Amsterdam", blurb: "Largest Dutch crypto exchange.", functions: ["engineering", "product", "data", "operations"] },

  // ── Tech & Software ──────────────────────────────────────────────────
  { name: "Booking.com", industry: "tech", city: "Amsterdam", blurb: "The Netherlands' biggest tech employer; travel platform.", functions: ["engineering", "product", "data", "finance_fpa", "sales_marketing", "operations"], careersUrl: "https://careers.booking.com" },
  { name: "Uber", industry: "tech", city: "Amsterdam", blurb: "EMEA headquarters — operations, finance and engineering hub.", functions: ["engineering", "product", "data", "finance_fpa", "operations", "sales_marketing"], careersUrl: "https://www.uber.com/careers" },
  { name: "Netflix", industry: "tech", city: "Amsterdam", blurb: "EMEA headquarters of the streaming giant.", functions: ["finance_fpa", "sales_marketing", "data", "operations", "hr_legal"], careersUrl: "https://jobs.netflix.com" },
  { name: "Google", industry: "tech", city: "Amsterdam", blurb: "Dutch office: sales, cloud and marketing (engineering mostly abroad).", functions: ["sales_marketing", "data", "strategy", "operations"], careersUrl: "https://careers.google.com" },
  { name: "Microsoft", industry: "tech", city: "Schiphol", blurb: "Dutch subsidiary: cloud sales, partner and consulting roles.", functions: ["sales_marketing", "data", "engineering", "operations"], careersUrl: "https://careers.microsoft.com" },
  { name: "Amazon", registerName: "Amazon Development Center Netherlands", industry: "tech", city: "Amsterdam", blurb: "Development centre plus retail/AWS commercial teams.", functions: ["engineering", "data", "product", "sales_marketing", "operations"], careersUrl: "https://www.amazon.jobs" },
  { name: "Databricks", industry: "tech", city: "Amsterdam", blurb: "European engineering hub of the data & AI platform.", functions: ["engineering", "data", "sales_marketing"], careersUrl: "https://www.databricks.com/company/careers" },
  { name: "Elastic", registerName: "Elasticsearch", industry: "tech", city: "Amsterdam", blurb: "Search & observability company behind Elasticsearch.", functions: ["engineering", "product", "sales_marketing"], careersUrl: "https://www.elastic.co/careers" },
  { name: "Miro", registerName: "RealtimeBoard", industry: "tech", city: "Amsterdam", blurb: "Visual collaboration platform; Amsterdam is a main hub.", functions: ["engineering", "product", "data", "sales_marketing"], careersUrl: "https://miro.com/careers/" },
  { name: "TomTom", industry: "tech", city: "Amsterdam", blurb: "Location technology and maps.", functions: ["engineering", "product", "data", "finance_fpa"], careersUrl: "https://www.tomtom.com/careers/" },
  { name: "Salesforce", registerName: "SFDC", industry: "tech", city: "Amsterdam", blurb: "CRM leader; Dutch office covers sales, strategy and solution roles.", functions: ["sales_marketing", "strategy", "data", "operations"], careersUrl: "https://careers.salesforce.com" },
  { name: "Atlassian", industry: "tech", city: "Amsterdam", blurb: "Amsterdam engineering office of the Jira/Confluence maker.", functions: ["engineering", "product", "sales_marketing"] },
  { name: "Exact", industry: "tech", city: "Delft", blurb: "Business software for SMEs and accountants.", functions: ["engineering", "product", "sales_marketing", "finance_fpa"] },
  // Mendix B.V. dropped out of the register (July 2026 update). Siemens owns
  // Mendix, and its Dutch Digital-Industries entity is what appears now, so the
  // badge resolves to that — hover the badge to see the exact register entry.
  { name: "Mendix (Siemens)", registerName: "Siemens Industry Software Netherlands", industry: "tech", city: "Rotterdam", blurb: "Low-code platform, part of Siemens; engineering HQ in Rotterdam.", functions: ["engineering", "product", "sales_marketing"] },

  // ── Consumer & Retail ────────────────────────────────────────────────
  { name: "Heineken", industry: "consumer", city: "Amsterdam", blurb: "Global brewer; famous international graduate programme.", functions: ["finance_fpa", "strategy", "sales_marketing", "data", "operations", "hr_legal"], careersUrl: "https://careers.theheinekencompany.com" },
  { name: "Unilever", industry: "consumer", city: "Rotterdam", blurb: "Consumer goods giant; finance and supply-chain leadership tracks.", functions: ["finance_fpa", "strategy", "sales_marketing", "data", "operations", "hr_legal"], careersUrl: "https://careers.unilever.com" },
  { name: "Ahold Delhaize", registerName: "Koninklijke Ahold Delhaize", industry: "consumer", city: "Zaandam", blurb: "Global food retailer (Albert Heijn, bol, US brands).", functions: ["finance_fpa", "strategy", "data", "operations", "sales_marketing"] },
  { name: "JDE Peet's", industry: "consumer", city: "Amsterdam", blurb: "World's largest pure-play coffee company.", functions: ["finance_fpa", "sales_marketing", "strategy", "operations"] },
  { name: "FrieslandCampina", registerName: "Koninklijke FrieslandCampina", industry: "consumer", city: "Amersfoort", blurb: "Dairy cooperative multinational.", functions: ["finance_fpa", "sales_marketing", "data", "operations"] },
  { name: "Nike EHQ", registerName: "Nike Retail", industry: "consumer", city: "Hilversum", blurb: "European headquarters of Nike.", functions: ["finance_fpa", "sales_marketing", "data", "operations", "strategy"], careersUrl: "https://jobs.nike.com" },
  { name: "Suitsupply", registerName: "Suit Supply", industry: "consumer", city: "Amsterdam", blurb: "Dutch tailoring brand with global retail footprint.", functions: ["finance_fpa", "sales_marketing", "data", "operations"] },
  { name: "Rituals", industry: "consumer", city: "Amsterdam", blurb: "Fast-growing cosmetics and lifestyle brand.", functions: ["finance_fpa", "sales_marketing", "operations", "data"] },
  { name: "Tony's Chocolonely", registerName: "Tony's Team", industry: "consumer", city: "Amsterdam", blurb: "Impact-driven chocolate brand.", functions: ["finance_fpa", "sales_marketing", "operations"] },
  { name: "Just Eat Takeaway.com", registerName: "Takeaway.com", industry: "consumer", city: "Amsterdam", blurb: "Food-delivery platform born in NL.", functions: ["engineering", "product", "data", "finance_fpa", "sales_marketing", "operations"], careersUrl: "https://careers.justeattakeaway.com" },
  { name: "Picnic", industry: "consumer", city: "Amsterdam", blurb: "App-only supermarket; big tech and analytics teams.", functions: ["engineering", "data", "product", "operations", "finance_fpa"] },
  { name: "Coolblue", industry: "consumer", city: "Rotterdam", blurb: "Beloved Dutch electronics retailer.", functions: ["engineering", "data", "sales_marketing", "operations", "finance_fpa"] },
  { name: "bol", registerName: "bol.com", industry: "consumer", city: "Utrecht", blurb: "Biggest online retail platform of the Benelux (Ahold Delhaize).", functions: ["engineering", "data", "product", "sales_marketing", "finance_fpa"] },

  // ── Energy ───────────────────────────────────────────────────────────
  { name: "Shell", registerName: "Shell International", industry: "energy", city: "The Hague", blurb: "Energy supermajor; trading, finance and engineering in NL.", functions: ["front_office", "finance_fpa", "strategy", "engineering", "data", "operations"], careersUrl: "https://www.shell.com/careers" },
  { name: "Vattenfall", industry: "energy", city: "Amsterdam", blurb: "Swedish utility, major Dutch operations; fossil-free push.", functions: ["finance_fpa", "engineering", "data", "operations", "sales_marketing"] },
  { name: "Eneco", industry: "energy", city: "Rotterdam", blurb: "Sustainable energy company (Mitsubishi-owned).", functions: ["finance_fpa", "engineering", "data", "operations"] },
  { name: "TenneT", industry: "energy", city: "Arnhem", blurb: "Dutch-German high-voltage grid operator; huge investment agenda.", functions: ["finance_fpa", "engineering", "operations", "strategy"] },
  { name: "SBM Offshore", industry: "energy", city: "Schiedam", blurb: "Floating offshore energy systems.", functions: ["engineering", "finance_fpa", "operations"] },
  { name: "Fugro", industry: "energy", city: "Leidschendam", blurb: "Geo-data specialist for energy and infrastructure.", functions: ["engineering", "data", "finance_fpa", "operations"] },
  { name: "Vopak", registerName: "Koninklijke Vopak", industry: "energy", city: "Rotterdam", blurb: "World's largest independent tank storage company.", functions: ["finance_fpa", "operations", "engineering", "strategy"] },

  // ── Health & Pharma ──────────────────────────────────────────────────
  { name: "Philips", registerName: "Koninklijke Philips", industry: "health", city: "Amsterdam", blurb: "Health-technology multinational.", functions: ["engineering", "product", "data", "finance_fpa", "sales_marketing", "strategy"], careersUrl: "https://www.careers.philips.com" },
  { name: "MSD", registerName: "Merck Sharp & Dohme", industry: "health", city: "Haarlem", blurb: "Pharma manufacturing and R&D sites across NL.", functions: ["engineering", "data", "operations", "finance_fpa"] },
  { name: "Johnson & Johnson (Janssen)", registerName: "Janssen Biologics", industry: "health", city: "Leiden", blurb: "Vaccines and biologics campus in Leiden.", functions: ["engineering", "data", "operations", "finance_fpa"], careersUrl: "https://careers.jnj.com" },
  { name: "Danone Nutricia", registerName: "Nutricia", industry: "health", city: "Utrecht", blurb: "Specialised-nutrition research and production.", functions: ["engineering", "data", "operations", "finance_fpa", "sales_marketing"] },
  { name: "Galapagos", industry: "health", city: "Leiden", blurb: "Biotech focused on immunology and oncology.", functions: ["engineering", "data", "operations"] },
  { name: "Genmab", industry: "health", city: "Utrecht", blurb: "Antibody-therapeutics biotech.", functions: ["engineering", "data", "operations"] },
  { name: "Amgen", industry: "health", city: "Breda", blurb: "Biotech supply and commercial hub for Europe.", functions: ["operations", "finance_fpa", "data"] },

  // ── Semiconductors & Hardware ────────────────────────────────────────
  { name: "ASML", industry: "hardware", city: "Veldhoven", blurb: "Lithography monopoly; NL's most valuable company, hires globally.", functions: ["engineering", "data", "finance_fpa", "operations", "strategy"], careersUrl: "https://www.asml.com/careers" },
  { name: "NXP Semiconductors", industry: "hardware", city: "Eindhoven", blurb: "Automotive and secure-connectivity chips.", functions: ["engineering", "data", "finance_fpa", "operations"] },
  { name: "ASM International", industry: "hardware", city: "Almere", blurb: "Semiconductor deposition equipment.", functions: ["engineering", "data", "finance_fpa", "operations"] },
  { name: "Besi", registerName: "BE Semiconductor Industries", industry: "hardware", city: "Duiven", blurb: "Chip assembly and packaging equipment.", functions: ["engineering", "finance_fpa", "operations"] },
  { name: "Thermo Fisher Scientific", industry: "hardware", city: "Eindhoven", blurb: "Electron microscopy centre of excellence.", functions: ["engineering", "data", "operations"], careersUrl: "https://jobs.thermofisher.com" },
  { name: "Signify", industry: "hardware", city: "Eindhoven", blurb: "World leader in lighting (ex-Philips Lighting).", functions: ["engineering", "finance_fpa", "sales_marketing", "operations"] },
  { name: "Prodrive Technologies", industry: "hardware", city: "Son", blurb: "High-tech electronics manufacturer.", functions: ["engineering", "operations"] },

  // ── Logistics & Mobility ─────────────────────────────────────────────
  { name: "KLM", registerName: "Koninklijke Luchtvaart Maatschappij", industry: "logistics", city: "Amstelveen", blurb: "Royal Dutch Airlines; finance, ops and engineering roles.", functions: ["finance_fpa", "operations", "engineering", "data", "strategy"] },
  { name: "Royal Schiphol Group", industry: "logistics", city: "Schiphol", blurb: "Operator of Amsterdam airport.", functions: ["finance_fpa", "operations", "engineering", "data"] },
  { name: "PostNL", industry: "logistics", city: "The Hague", blurb: "Dutch postal and parcel company.", functions: ["finance_fpa", "operations", "data", "engineering"] },
  { name: "Port of Rotterdam", registerName: "Havenbedrijf Rotterdam", industry: "logistics", city: "Rotterdam", blurb: "Authority of Europe's largest port.", functions: ["finance_fpa", "operations", "strategy", "data"] },
  { name: "Vanderlande", industry: "logistics", city: "Veghel", blurb: "Airport and warehouse automation leader.", functions: ["engineering", "operations", "finance_fpa", "data"] },
  { name: "Maersk", industry: "logistics", city: "Rotterdam", blurb: "Container shipping and logistics giant.", functions: ["operations", "finance_fpa", "data", "sales_marketing"], careersUrl: "https://www.maersk.com/careers" },

  // ── Media & Creative ─────────────────────────────────────────────────
  { name: "Elsevier (RELX)", registerName: "Elsevier", industry: "media", city: "Amsterdam", blurb: "Scientific publishing and analytics.", functions: ["product", "data", "engineering", "sales_marketing", "finance_fpa"] },
  { name: "Wolters Kluwer", industry: "media", city: "Alphen aan den Rijn", blurb: "Professional information and software.", functions: ["product", "data", "engineering", "finance_fpa", "sales_marketing"] },
  { name: "DEPT", industry: "media", city: "Amsterdam", blurb: "Global digital agency born in NL.", functions: ["sales_marketing", "engineering", "product", "data"] },
  { name: "WeTransfer", industry: "media", city: "Amsterdam", blurb: "File-sharing and creative tools.", functions: ["engineering", "product", "sales_marketing"] },
  { name: "Framer", industry: "media", city: "Amsterdam", blurb: "Design and website-building tool.", functions: ["engineering", "product", "sales_marketing"] },
  { name: "Guerrilla Games", registerName: "Guerrilla", industry: "media", city: "Amsterdam", blurb: "PlayStation studio behind Horizon.", functions: ["engineering", "product", "data"] },

  // ══ Expansion batch (all register-probed before inclusion) ═══════════

  // ── Tech & Software (global vendors, EMEA hubs, IT services) ────────
  { name: "Apple", registerName: "Apple Benelux", industry: "tech", city: "Amsterdam", functions: ["sales_marketing", "operations", "finance_fpa"], careersUrl: "https://jobs.apple.com" },
  { name: "Cisco", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "operations"] },
  { name: "IBM", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "sales_marketing", "operations"] },
  { name: "Oracle", industry: "tech", city: "Utrecht", functions: ["engineering", "sales_marketing", "data", "operations"] },
  { name: "SAP", industry: "tech", city: "Den Bosch", functions: ["engineering", "sales_marketing", "data", "operations"] },
  { name: "ServiceNow", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "product"] },
  { name: "Adobe", registerName: "Adobe Systems Benelux", industry: "tech", city: "Amsterdam", functions: ["sales_marketing", "data", "product"] },
  { name: "Palo Alto Networks", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "data"] },
  { name: "JetBrains", industry: "tech", city: "Amsterdam", blurb: "IDE maker (IntelliJ, PyCharm); Amsterdam is a core dev hub.", functions: ["engineering", "product", "sales_marketing"], careersUrl: "https://www.jetbrains.com/careers/" },
  { name: "Datadog", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing"] },
  { name: "MongoDB", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing"] },
  { name: "Zscaler", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing"] },
  { name: "Splunk", registerName: "Splunk Services Netherlands", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing"] },
  { name: "Workday", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "operations"] },
  { name: "Snowflake", registerName: "Snowflake Computing Netherlands", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "data"] },
  { name: "Cloudflare", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing"] },
  { name: "Infosys", registerName: "Infosys Limited", industry: "tech", city: "Amsterdam", blurb: "Indian IT giant; sponsors at scale for client projects.", functions: ["engineering", "data", "operations", "strategy"] },
  { name: "Tata Consultancy Services", industry: "tech", city: "Amsterdam", blurb: "One of NL's biggest kennismigrant employers.", functions: ["engineering", "data", "operations", "strategy"] },
  { name: "Cognizant", registerName: "Cognizant Technology Solutions Benelux", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "operations"] },
  { name: "Capgemini", industry: "tech", city: "Utrecht", functions: ["engineering", "data", "operations", "strategy"] },
  { name: "Wipro", registerName: "Wipro Limited", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "operations"] },
  { name: "HCL Technologies", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "operations"] },
  { name: "LTIMindtree", registerName: "LTIMindtree Limited", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "operations"] },
  { name: "Tech Mahindra", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "operations"] },
  { name: "Xebia", registerName: "Xebia Nederland", industry: "tech", city: "Hilversum", functions: ["engineering", "data", "strategy"] },
  { name: "Software Improvement Group", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "strategy"] },
  { name: "KPN", industry: "tech", city: "Rotterdam", functions: ["engineering", "data", "finance_fpa", "operations"] },
  { name: "Odido", industry: "tech", city: "The Hague", functions: ["engineering", "data", "sales_marketing", "operations"] },
  { name: "VodafoneZiggo", registerName: "VodafoneZiggo Employment", industry: "tech", city: "Utrecht", functions: ["engineering", "data", "sales_marketing", "finance_fpa"] },
  { name: "Ericsson", registerName: "Ericsson Telecommunicatie", industry: "tech", city: "Rijen", functions: ["engineering", "operations"] },
  { name: "Nokia", registerName: "Nokia Solutions and Networks", industry: "tech", city: "Hoofddorp", functions: ["engineering", "operations"] },
  { name: "Huawei", registerName: "Huawei Technologies (Netherlands)", industry: "tech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "operations"] },
  { name: "Fujitsu", registerName: "Fujitsu Technology Solutions", industry: "tech", city: "Maarssen", functions: ["engineering", "operations"] },
  { name: "NTT DATA", industry: "tech", city: "Amsterdam", functions: ["engineering", "data", "operations"] },

  // ── Finance & Banking (foreign banks, fund admin, PE, trading) ──────
  { name: "Citco", registerName: "Citco Nederland", industry: "finance", city: "Amsterdam", blurb: "Global hedge-fund administrator; big international hirer.", functions: ["finance_fpa", "operations", "data"] },
  { name: "Northern Trust", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations", "front_office"] },
  { name: "State Street", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations", "data"] },
  { name: "BNY Mellon", registerName: "Bank of New York Mellon", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations", "front_office"] },
  { name: "J.P. Morgan", registerName: "J.P. Morgan SE Amsterdam Branch", industry: "finance", city: "Amsterdam", blurb: "EU trading & banking hub built post-Brexit.", functions: ["front_office", "finance_fpa", "data", "operations"] },
  { name: "Goldman Sachs", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "BlackRock", registerName: "BlackRock (Netherlands)", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "data", "operations"] },
  { name: "UBS", registerName: "UBS Europe", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Deutsche Bank", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "BNP Paribas", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "CACEIS", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations"] },
  { name: "MUFG Bank", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Mizuho Bank", registerName: "Mizuho Bank Europe", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "SMBC", registerName: "SMBC Bank EU", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "ICBC", registerName: "ICBC Amsterdam Branch", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Bank of China", industry: "finance", city: "Rotterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "China Construction Bank", industry: "finance", city: "Amsterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "TMF Group", industry: "finance", city: "Amsterdam", blurb: "Fund & corporate services; hires many internationals.", functions: ["finance_fpa", "operations", "hr_legal"] },
  { name: "Intertrust (CSC)", registerName: "Intertrust Group", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations", "hr_legal"] },
  { name: "Vistra", registerName: "Vistra Corporate Services", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations", "hr_legal"] },
  { name: "Alter Domus", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations"] },
  { name: "JTC Group", registerName: "JTC Institutional Services Netherlands", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations"] },
  { name: "Bolder Group", registerName: "Bolder Business Services", industry: "finance", city: "Amsterdam", functions: ["finance_fpa", "operations"] },
  { name: "MN", registerName: "Mn Services", industry: "finance", city: "The Hague", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Cardano", registerName: "Cardano Risk Management", industry: "finance", city: "Rotterdam", functions: ["front_office", "data", "finance_fpa"] },
  { name: "BNG Bank", industry: "finance", city: "The Hague", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "a.s.r.", registerName: "ASR Nederland", industry: "finance", city: "Utrecht", functions: ["finance_fpa", "front_office", "data", "operations"] },
  { name: "Athora", registerName: "Athora Netherlands", industry: "finance", city: "Amstelveen", functions: ["finance_fpa", "front_office", "operations"] },
  { name: "Allianz", registerName: "Allianz Benelux", industry: "finance", city: "Rotterdam", functions: ["finance_fpa", "data", "operations"] },
  { name: "Egeria", registerName: "Egeria Group Services", industry: "finance", city: "Amsterdam", blurb: "Dutch mid-market private equity.", functions: ["front_office", "finance_fpa"] },
  { name: "Gilde Healthcare", registerName: "Gilde Healthcare Partners", industry: "finance", city: "Utrecht", functions: ["front_office", "finance_fpa"] },
  { name: "Main Capital Partners", industry: "finance", city: "The Hague", blurb: "Software-focused PE.", functions: ["front_office", "finance_fpa", "data"] },
  { name: "Da Vinci Derivatives", industry: "finance", city: "Amsterdam", blurb: "Options market maker.", functions: ["front_office", "data", "engineering"] },
  { name: "Tower Research Capital", registerName: "Tower Research Capital Europe", industry: "finance", city: "Amsterdam", functions: ["front_office", "data", "engineering"] },
  { name: "DRW", registerName: "DRW Europe", industry: "finance", city: "Amsterdam", functions: ["front_office", "data", "engineering"] },

  // ── Payments & Fintech ───────────────────────────────────────────────
  { name: "Stripe", industry: "fintech", city: "Amsterdam", functions: ["engineering", "sales_marketing", "operations"] },
  { name: "Klarna", industry: "fintech", city: "Amsterdam", functions: ["engineering", "data", "sales_marketing"] },
  { name: "Ebury", industry: "fintech", city: "Amsterdam", functions: ["sales_marketing", "finance_fpa", "operations"] },
  { name: "Finom", registerName: "FINOM Payments", industry: "fintech", city: "Amsterdam", functions: ["engineering", "product", "sales_marketing"] },
  { name: "Silverflow", industry: "fintech", city: "Amsterdam", functions: ["engineering", "product"] },
  { name: "Fourthline", industry: "fintech", city: "Amsterdam", blurb: "KYC / anti-fraud technology.", functions: ["engineering", "data", "product", "operations"] },
  { name: "Ohpen", registerName: "OHPEN Services", industry: "fintech", city: "Amsterdam", functions: ["engineering", "product", "operations"] },
  { name: "CM.com", registerName: "CM.com International", industry: "fintech", city: "Breda", functions: ["engineering", "product", "sales_marketing", "finance_fpa"] },
  { name: "PayU", industry: "fintech", city: "Hoofddorp", functions: ["engineering", "product", "operations"] },
  { name: "Worldline", industry: "fintech", city: "Utrecht", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "BUX", registerName: "BUX Technology", industry: "fintech", city: "Amsterdam", functions: ["engineering", "product", "data"] },
  { name: "DEGIRO", industry: "fintech", city: "Amsterdam", functions: ["engineering", "product", "operations", "finance_fpa"] },

  // ── Consumer & Retail ────────────────────────────────────────────────
  { name: "IKEA", industry: "consumer", city: "Amsterdam", functions: ["finance_fpa", "sales_marketing", "operations", "data"] },
  { name: "H&M", registerName: "Hennes & Mauritz", industry: "consumer", city: "Amsterdam", functions: ["sales_marketing", "operations", "finance_fpa"] },
  { name: "HelloFresh", registerName: "HelloFresh Benelux", industry: "consumer", city: "Amsterdam", functions: ["operations", "data", "sales_marketing", "finance_fpa"] },
  { name: "Red Bull", registerName: "Red Bull Nederland", industry: "consumer", city: "Amsterdam", functions: ["sales_marketing", "finance_fpa", "operations"] },
  { name: "PVH (Tommy Hilfiger / Calvin Klein)", registerName: "PVH", industry: "consumer", city: "Amsterdam", blurb: "European HQ of Tommy Hilfiger & Calvin Klein — very international.", functions: ["finance_fpa", "sales_marketing", "data", "operations", "strategy"] },
  { name: "G-Star RAW", registerName: "G-Star Raw", industry: "consumer", city: "Amsterdam", functions: ["sales_marketing", "finance_fpa", "operations"] },
  { name: "Under Armour", registerName: "Under Armour Europe", industry: "consumer", city: "Amsterdam", blurb: "EMEA headquarters.", functions: ["sales_marketing", "finance_fpa", "operations", "data"] },
  { name: "ASICS", registerName: "ASICS Europe", industry: "consumer", city: "Hoofddorp", blurb: "EMEA headquarters.", functions: ["sales_marketing", "finance_fpa", "operations", "data"] },
  { name: "Patagonia", registerName: "Patagonia Europe", industry: "consumer", city: "Amsterdam", blurb: "European HQ of the outdoor brand.", functions: ["sales_marketing", "operations", "finance_fpa"] },
  { name: "Mars", registerName: "Mars Nederland", industry: "consumer", city: "Veghel", functions: ["operations", "finance_fpa", "sales_marketing", "engineering"] },
  { name: "Mondelez", registerName: "Mondelez Nederland Services", industry: "consumer", city: "Amsterdam", functions: ["finance_fpa", "sales_marketing", "operations"] },
  { name: "Coca-Cola", registerName: "Coca-Cola Nederland", industry: "consumer", city: "Rotterdam", functions: ["sales_marketing", "finance_fpa", "operations"] },
  { name: "PepsiCo", registerName: "PepsiCo Nederland", industry: "consumer", city: "Utrecht", functions: ["finance_fpa", "sales_marketing", "operations", "data"] },
  { name: "AB InBev", registerName: "InBev Nederland", industry: "consumer", city: "Breda", functions: ["finance_fpa", "sales_marketing", "operations"] },
  { name: "Royal Swinkels", industry: "consumer", city: "Lieshout", functions: ["operations", "finance_fpa", "sales_marketing"] },
  { name: "Vivera", industry: "consumer", city: "Holten", blurb: "Plant-based food maker.", functions: ["operations", "engineering", "finance_fpa"] },
  { name: "Refresco", registerName: "Refresco Benelux", industry: "consumer", city: "Rotterdam", functions: ["operations", "finance_fpa", "engineering"] },
  { name: "Bugaboo", industry: "consumer", city: "Amsterdam", functions: ["product", "engineering", "sales_marketing", "finance_fpa"] },
  { name: "Versuni (ex-Philips Domestic)", registerName: "Versuni Netherlands", industry: "consumer", city: "Amsterdam", functions: ["product", "engineering", "sales_marketing", "finance_fpa"] },

  // ── Health & Pharma ──────────────────────────────────────────────────
  { name: "AstraZeneca", industry: "health", city: "The Hague", functions: ["sales_marketing", "data", "operations", "finance_fpa"] },
  { name: "Pfizer", industry: "health", city: "Capelle a/d IJssel", functions: ["sales_marketing", "operations", "finance_fpa"] },
  { name: "Novartis", industry: "health", city: "Amsterdam", functions: ["sales_marketing", "data", "operations"] },
  { name: "Roche", registerName: "Roche Nederland", industry: "health", city: "Woerden", functions: ["sales_marketing", "data", "operations"] },
  { name: "Sanofi", industry: "health", city: "Amsterdam", functions: ["sales_marketing", "operations"] },
  { name: "Abbott", industry: "health", city: "Weesp", blurb: "Multiple large NL manufacturing sites.", functions: ["engineering", "operations", "data", "finance_fpa"] },
  { name: "AbbVie", industry: "health", city: "Hoofddorp", functions: ["sales_marketing", "operations", "finance_fpa"] },
  { name: "Medtronic", industry: "health", city: "Heerlen", blurb: "Large international ops hub in Heerlen.", functions: ["operations", "finance_fpa", "data", "engineering"] },
  { name: "Boston Scientific", industry: "health", city: "Kerkrade", functions: ["operations", "engineering", "finance_fpa"] },
  { name: "Stryker", registerName: "Stryker Nederland", industry: "health", city: "Amsterdam", functions: ["operations", "sales_marketing", "finance_fpa"] },
  { name: "Baxter", industry: "health", city: "Utrecht", functions: ["operations", "sales_marketing", "finance_fpa"] },
  { name: "uniQure", registerName: "uniQure biopharma", industry: "health", city: "Amsterdam", blurb: "Gene-therapy biotech.", functions: ["engineering", "data", "operations"] },
  { name: "Kite Pharma (Gilead)", registerName: "Kite Pharma EU", industry: "health", city: "Hoofddorp", blurb: "Cell-therapy manufacturing for Europe.", functions: ["engineering", "operations", "data"] },
  { name: "DSM-Firmenich", registerName: "DSM NL Services", industry: "health", city: "Maastricht", blurb: "Nutrition, health and beauty science.", functions: ["engineering", "data", "finance_fpa", "operations", "strategy"] },
  { name: "Merus", industry: "health", city: "Utrecht", blurb: "Oncology antibody biotech.", functions: ["engineering", "data", "operations"] },
  { name: "Pharming", registerName: "Pharming Group", industry: "health", city: "Leiden", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Synthon", industry: "health", city: "Nijmegen", functions: ["engineering", "operations"] },
  { name: "Teva", registerName: "Teva Pharmaceuticals Europe", industry: "health", city: "Haarlem", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Astellas", industry: "health", city: "Leiden", functions: ["engineering", "operations", "sales_marketing"] },
  { name: "Organon", industry: "health", city: "Oss", blurb: "Women's-health pharma with major Oss site.", functions: ["engineering", "operations", "finance_fpa", "data"] },

  // ── Semiconductors & Hardware ────────────────────────────────────────
  { name: "Nexperia", industry: "hardware", city: "Nijmegen", blurb: "High-volume chipmaker (ex-NXP standard products).", functions: ["engineering", "operations", "data", "finance_fpa"] },
  { name: "Ampleon", registerName: "Ampleon Netherlands", industry: "hardware", city: "Nijmegen", functions: ["engineering", "operations"] },
  { name: "VDL Groep", registerName: "VDL", industry: "hardware", city: "Eindhoven", blurb: "Industrial family conglomerate; ASML supplier.", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Additive Industries", industry: "hardware", city: "Eindhoven", blurb: "Industrial metal 3D printing.", functions: ["engineering", "operations"] },
  { name: "Sioux Technologies", industry: "hardware", city: "Eindhoven", functions: ["engineering", "data"] },
  { name: "Demcon", industry: "hardware", city: "Enschede", functions: ["engineering", "data"] },
  { name: "TE Connectivity", registerName: "TE Connectivity Nederland", industry: "hardware", city: "Den Bosch", functions: ["engineering", "operations", "sales_marketing"] },
  { name: "Canon Production Printing", industry: "hardware", city: "Venlo", blurb: "Ex-Océ; big international R&D site.", functions: ["engineering", "data", "operations"] },
  { name: "Nedap", industry: "hardware", city: "Groenlo", functions: ["engineering", "product", "data"] },
  { name: "Kulicke & Soffa", registerName: "Kulicke & Soffa Netherlands", industry: "hardware", city: "Eindhoven", functions: ["engineering", "operations"] },
  { name: "Axelera AI", industry: "hardware", city: "Eindhoven", blurb: "AI-chip startup.", functions: ["engineering", "data"] },
  { name: "SMART Photonics", industry: "hardware", city: "Eindhoven", functions: ["engineering", "operations"] },
  { name: "Thales", registerName: "Thales Nederland", industry: "hardware", city: "Hengelo", functions: ["engineering", "data", "operations"] },
  { name: "Marel", registerName: "Marel Holding", industry: "hardware", city: "Boxmeer", blurb: "Food-processing machinery.", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Lely", industry: "hardware", city: "Maassluis", blurb: "Agri robotics (milking robots).", functions: ["engineering", "product", "data"] },

  // ── Energy (incl. trading & offshore) ────────────────────────────────
  { name: "bp", registerName: "BP Raffinaderij Rotterdam", industry: "energy", city: "Rotterdam", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "TotalEnergies", registerName: "TotalEnergies EP Nederland", industry: "energy", city: "The Hague", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Ørsted", registerName: "Orsted Wind Power", industry: "energy", city: "The Hague", blurb: "Offshore wind developer.", functions: ["engineering", "finance_fpa", "operations", "strategy"] },
  { name: "Uniper", registerName: "Uniper Benelux", industry: "energy", city: "Rotterdam", functions: ["front_office", "engineering", "finance_fpa"] },
  { name: "Gasunie", industry: "energy", city: "Groningen", functions: ["engineering", "finance_fpa", "operations", "strategy"] },
  { name: "Stedin", registerName: "Stedin Netbeheer", industry: "energy", city: "Rotterdam", functions: ["engineering", "data", "operations", "finance_fpa"] },
  { name: "Alliander", industry: "energy", city: "Arnhem", functions: ["engineering", "data", "operations", "finance_fpa"] },
  { name: "Nobian", registerName: "Nobian Chemicals", industry: "energy", city: "Amersfoort", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "LyondellBasell", registerName: "LyondellBasell Industries Holdings", industry: "energy", city: "Rotterdam", blurb: "Chemicals giant; big Rotterdam hub.", functions: ["engineering", "operations", "finance_fpa", "data"] },
  { name: "Shin-Etsu", registerName: "Shin-Etsu PVC", industry: "energy", city: "Amsterdam", functions: ["engineering", "operations"] },
  { name: "Huntsman", registerName: "Huntsman Holland", industry: "energy", city: "Rotterdam", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Tronox", registerName: "Tronox Pigments", industry: "energy", city: "Rotterdam", functions: ["engineering", "operations"] },
  { name: "Neste", registerName: "Neste Netherlands", industry: "energy", city: "Rotterdam", blurb: "Renewable fuels refinery.", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Varo Energy", industry: "energy", city: "Rotterdam", functions: ["front_office", "finance_fpa", "operations"] },
  { name: "Vitol", registerName: "Vitol SA Rotterdam Branch", industry: "energy", city: "Rotterdam", blurb: "World's largest independent energy trader.", functions: ["front_office", "finance_fpa", "operations", "data"] },
  { name: "Trafigura", registerName: "Trafigura Beheer", industry: "energy", city: "Amsterdam", blurb: "Commodity trading major.", functions: ["front_office", "finance_fpa", "operations", "data"] },
  { name: "Gunvor", registerName: "Gunvor Energy Rotterdam", industry: "energy", city: "Rotterdam", functions: ["front_office", "engineering", "operations", "finance_fpa"] },
  { name: "Van Oord", registerName: "Van Oord Personeels", industry: "energy", city: "Rotterdam", blurb: "Marine contracting & offshore wind.", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Boskalis", registerName: "Baggermaatschappij Boskalis", industry: "energy", city: "Papendrecht", blurb: "Dredging & offshore energy services.", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "ENGIE", registerName: "ENGIE Energie Nederland", industry: "energy", city: "Zwolle", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Essent", industry: "energy", city: "Den Bosch", functions: ["data", "sales_marketing", "finance_fpa", "operations"] },
  { name: "Air Products", registerName: "Air Products Nederland", industry: "energy", city: "Rotterdam", blurb: "Industrial gases & hydrogen.", functions: ["engineering", "operations"] },
  { name: "OCI Global", registerName: "OCI", industry: "energy", city: "Amsterdam", blurb: "Fertilizers, methanol & hydrogen; Amsterdam HQ.", functions: ["finance_fpa", "front_office", "operations", "strategy"] },
  { name: "Yara", registerName: "Yara Sluiskil", industry: "energy", city: "Sluiskil", functions: ["engineering", "operations"] },
  { name: "Alfen", industry: "energy", city: "Almere", blurb: "EV charging & grid tech.", functions: ["engineering", "product", "operations", "finance_fpa"] },

  // ── Logistics & Mobility ─────────────────────────────────────────────
  { name: "Tesla", registerName: "Tesla International", industry: "logistics", city: "Amsterdam", blurb: "EMEA headquarters: finance, ops, sales, service engineering.", functions: ["finance_fpa", "operations", "sales_marketing", "data", "engineering"], careersUrl: "https://www.tesla.com/careers" },
  { name: "DHL", registerName: "DHL Express", industry: "logistics", city: "Amsterdam", functions: ["operations", "data", "finance_fpa", "engineering"] },
  { name: "Kuehne + Nagel", industry: "logistics", city: "Rotterdam", functions: ["operations", "finance_fpa", "data"] },
  { name: "DSV", registerName: "DSV Road", industry: "logistics", city: "Venlo", functions: ["operations", "finance_fpa", "data"] },
  { name: "GXO Logistics", registerName: "GXO Logistics Netherlands", industry: "logistics", city: "Eindhoven", functions: ["operations", "data", "engineering"] },
  { name: "CEVA Logistics", industry: "logistics", city: "Rotterdam", functions: ["operations", "finance_fpa", "data"] },
  { name: "Rhenus", registerName: "Rhenus Air & Ocean", industry: "logistics", city: "Tilburg", functions: ["operations", "finance_fpa"] },
  { name: "DB Schenker", registerName: "Schenker Logistics", industry: "logistics", city: "Tilburg", functions: ["operations", "finance_fpa", "data"] },
  { name: "APM Terminals", registerName: "APM Terminals Management", industry: "logistics", city: "The Hague", blurb: "Maersk's global terminals HQ is in NL.", functions: ["operations", "finance_fpa", "engineering", "strategy"] },
  { name: "Transavia", registerName: "Transavia Airlines", industry: "logistics", city: "Schiphol", functions: ["operations", "data", "finance_fpa", "engineering"] },
  { name: "Damen Shipyards", registerName: "Damen", industry: "logistics", city: "Gorinchem", blurb: "Family-owned global shipbuilder.", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Heerema Marine Contractors", registerName: "Heerema", industry: "logistics", city: "Leiden", functions: ["engineering", "operations", "finance_fpa"] },
  { name: "Allseas", registerName: "Allseas Engineering", industry: "logistics", city: "Delft", blurb: "Offshore pipelay & heavy lift.", functions: ["engineering", "operations"] },
  { name: "GKN Fokker", registerName: "GKN Fokker Aerospace", industry: "logistics", city: "Papendrecht", functions: ["engineering", "operations"] },
  { name: "Airbus", registerName: "Airbus Netherlands", industry: "logistics", city: "Leiden", functions: ["engineering", "operations"] },

  // ── Consulting ───────────────────────────────────────────────────────
  { name: "Oliver Wyman", industry: "consulting", city: "Amsterdam", functions: ["strategy", "data", "finance_fpa"] },
  { name: "Alvarez & Marsal", registerName: "Alvarez & Marsal Benelux", industry: "consulting", city: "Amsterdam", blurb: "Restructuring, transactions and performance improvement.", functions: ["strategy", "finance_fpa", "data"] },
  { name: "FTI Consulting", industry: "consulting", city: "Amsterdam", functions: ["strategy", "finance_fpa", "data"] },
  { name: "Simon-Kucher", registerName: "Simon-Kucher & Partners", industry: "consulting", city: "Amsterdam", blurb: "Pricing & growth strategy.", functions: ["strategy", "data", "sales_marketing"] },
  { name: "Arthur D. Little", registerName: "Arthur D. Little Benelux", industry: "consulting", city: "Rotterdam", functions: ["strategy", "data"] },
  { name: "Sia Partners", industry: "consulting", city: "Amsterdam", functions: ["strategy", "data", "operations"] },
  { name: "Aon", registerName: "Aon Groep Nederland", industry: "consulting", city: "Rotterdam", functions: ["strategy", "finance_fpa", "data", "hr_legal"] },
  { name: "Ecorys", registerName: "ECORYS Nederland", industry: "consulting", city: "Rotterdam", blurb: "Economics & policy consulting.", functions: ["strategy", "data"] },

  // ── Media & Creative ─────────────────────────────────────────────────
  { name: "TikTok", registerName: "TikTok Netherlands", industry: "media", city: "Amsterdam", functions: ["sales_marketing", "data", "operations", "hr_legal"] },
  { name: "Spotify", registerName: "Spotify Netherlands", industry: "media", city: "Amsterdam", functions: ["sales_marketing", "data", "operations"] },
  { name: "Nixxes Software", industry: "media", city: "Utrecht", blurb: "PlayStation PC-port studio.", functions: ["engineering", "product"] },
  { name: "Banijay Benelux", registerName: "Banijay Benelux Holding", industry: "media", city: "Amsterdam", functions: ["sales_marketing", "operations", "finance_fpa"] },
];
